### ISSUE TITLE
normalize URLs - remove the trailing /

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#37]
We should generate all links w/o the trailing `/`.

Trailing slash URLs should redirect to the normalized version w/o it:

`https://blog.dvc.org/july-19-dvc-heartbeat/` ---301-->  `https://blog.dvc.org/july-19-dvc-heartbeat`

*Relevant discussion on this:*

https://github.com/gatsbyjs/gatsby/issues/9207

**Comment by shcheklein** [comment]
Updated the description.

**Comment by shcheklein** [comment]
@iAdramelk seeing something like this on Twitter card and Facebook OG debugger:

<img width="703" alt="Screen Shot 2020-01-22 at 3 41 30 PM" src="https://user-images.githubusercontent.com/3659196/72944490-e3a0a480-3d2d-11ea-9554-27943d4cd633.png">

Reopening this for now to figure out.

**Comment by iAdramelk** [comment]
Looks like a redirect on Netlify side. Will check settings.

**Comment by iAdramelk** [comment]
@shcheklein  Checked settings and redirects are disabled. Also then I try to enter https://blog.dvc.org/january-20-dvc-heartbeat , I'm not redirected. Can you try to enter url yourself and see if you are redirected?

**Comment by shcheklein** [comment]
@iAdramelk that what I get in my browser: 

<img width="1292" alt="Screen Shot 2020-01-23 at 4 16 45 PM" src="https://user-images.githubusercontent.com/3659196/73035078-cf2add80-3dfb-11ea-81b2-8c692d582fda.png">


and you can indeed see for a moment that it adds `/` at the end and then removes it. Not sure what is happening here.

**Comment by fabiosantoscode** [comment]
Can reproduce too, with firefox and curl -I both.

According to [this screenshot](https://community.netlify.com/t/trailing-slash-redirect-rule-not-working/3215/8) there seems to be an option in netlify called "pretty URLs" which can add trailing slashes. Is it enabled? CC @iAdramelk

**Comment by cosmn** [comment]
@fabiosantoscode @iAdramelk It's not a Netlify issue, this behavior is also present in both the local production build / serve, and local development ( if you refresh the page, not hot reloading ).
It's related to the `express-static` as presented in this [gatsby issue](https://github.com/gatsbyjs/gatsby/issues/19543) whose [PR](https://github.com/gatsbyjs/gatsby/pull/19567) is not yet closed and merged.
I assumed Netlify would run an nginx to serve the static files, but it seems they execute `yarn serve` most likely with a caching layer on top for all requests / responses

@shcheklein the disappearing `/` is a `<Router>` redirect on the client-side, reverting to the correct path. It wont happen if you disable javascript, which suggests is a client-side behavior. 

I couldn't find a way to hook into gatsby's `express-static` to solve the issue on our end.
I'll continue digging.
Opinions ?

**Comment by fabiosantoscode** [comment]
It's odd @cosmn, but I can't reproduce the behaviour at all locally (using `gatsby develop`), in either chrome or firefox. This is why I assumed it's a netlify issue. I tried reloading now and it didn't happen. And `curl -I` didn't show a redirect either.

Maybe we just wait for this PR to be closed?

**Comment by cosmn** [comment]
@fabiosantoscode it's an odd one indeed, but its there. PR is abandoned from the looks of it

Local development             |  Local production
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/26232682/73704536-0e123a80-46fc-11ea-8072-0059977cc18d.png) | ![image](https://user-images.githubusercontent.com/26232682/73704648-65180f80-46fc-11ea-9421-5995c572bbd2.png)

**Comment by fabiosantoscode** [comment]
I've been able to repro this in local production.

I've tried simply using [serve](https://www.npmjs.com/package/serve) to serve the `public` directory after a build, and everything seems to work fine. No redirects at the trailing slash, but adding a `public/serve.json` file with `"trailingSlash": false` in it removes the trailing slash nicely with a 301. `serve.json` also allows you to customise a lot of behaviour.

An alternative solution would be to attempt to send a PR to express itself, and add an option that removes the trailing slash with a redirect, as opposed to adding it. For sure more people would find this useful.

**Comment by cosmn** [comment]
@fabiosantoscode I'm glad we're on the same page now.
Using [serve](https://www.npmjs.com/package/serve) or any other static serving implementation, either custom or already built, implies leaving the gatsby environment, which I would keep it as a last resort. I agree that we'll have full control of the static serving pipeline, but we may introduce side-effects difficult to anticipate at the moment.

In regards to contributing to either [gatsby](https://github.com/gatsbyjs/gatsby) or [static-serve](https://github.com/expressjs/serve-static), or even [send](https://github.com/pillarjs/send), it's not that easily achieved because of the amount on code build on top of it. [Michal Piechowiak](https://github.com/pieh), one of gatsby's contributor [did a very good summary](https://github.com/gatsbyjs/gatsby/pull/19567#discussion_r347506510) of the implications on this [abandoned PR](https://github.com/gatsbyjs/gatsby/pull/19567).

Keep in mind that the gatsby's entire output of static files relies on `static-serve` behavior in regards to directories, which makes this a core level problem.

**Comment by fabiosantoscode** [comment]
This is pretty bad :(

It might be hard to get a PR accepted in serve-static, but actually writing a good PR shouldn't be so hard. The whole module is just 200 lines and [this function](https://github.com/expressjs/serve-static/blob/master/index.js#L182-L210), which is responsible for redirects, could be modified to take an extra parameter and return a handler which does the opposite thing. Add a bunch of tests and :hammer: :hammer: :hammer: :medal_sports: we have a PR :)

I've added an issue on their end: https://github.com/expressjs/serve-static/issues/132

Barring that, I still believe that serve is our best option among the bunch. Gatsby's purpose is to create static websites, and a lot of people will certainly use generic static file hosting services to host them, such as amazon S3, or pushing to a CDN, which are cheap, easy and resilient ways of hosting a static website.

I agree that we might have some work in the future (adding some headers and whatnot) but I don't think that the gatsby team would introduce anything which would make it impractical to host gatsby websites in such a cost-effective and practical way, and force people to use their own command as a server.

**Comment by fabiosantoscode** [comment]
@cosmn Looks like sending a PR to serve-static is out of the question. Since it would effectively change how the file structure is perceived, they're not willing to accept it. I understand their point of view.

They did leave a suggestion to use `.html` and remove the extension using another option, which should work just fine, but I don't believe that is feasible for gatsby. It would be a massive breaking change.

**Comment by cosmn** [comment]
@fabiosantoscode You want too far with the issue on `serve-static` repo. The problem lies into gatsby's back yard, to which I just submitted a workable solution [on this PR](https://github.com/gatsbyjs/gatsby/pull/21203)

@shcheklein and @iAdramelk this is now on hold waiting for gatsby's contributors to reply.

**Comment by fabiosantoscode** [comment]
I thought they might want to have it. serve can remove trailing slashes like what we need.

**Comment by shcheklein** [comment]
Another issue with this is that Google according to its webmaster considers now URLs with slash at the end as original ones and w/o a slash as duplicates. Considering that our sitemap includes URLs w/o slash we potentially hit some SEO penalties.

**Comment by shcheklein** [comment]
Closed by #135 . Thanks @fabiosantoscode !
