### ISSUE TITLE
properly size post images

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#40]
Effective image size should 1/2 to make it sharp on retina screens. I suggest we always (?) make size 1/2 before we cut it into a certain box. No matter what.

**Comment by iAdramelk** [comment]
There is two types of images used in the blog right now: Header images, avatars and images inserted using markdown should work as described already. But images inserted by using html tags by hand and skipped by `gatsby` right now. I will try to make them work too.

**Comment by frontexpert** [comment]
Hi @shcheklein.
I didn't understand. Do you want to reduce the size of the image in the 50% before of process of gatsby-image that it? can you explain more to me?

**Comment by fabiosantoscode** [comment]
@frontexpert I think Ivan is talking about high pixel density screens like retina, phone and 4k screens.

This is often achieved using a `<picture>` element or `srcset` image attribute with multiple sources, which can help choose the right source image for the right screen, depending on pixel density and display size.

The gatsby-remark-images plugin seems to do this out of the box. https://www.gatsbyjs.org/packages/gatsby-remark-images

The question is whether our source images are large enough.

**Comment by shcheklein** [comment]
@fabiosantoscode yes, and the question is "if they are not large enough do not allow Gatsby to stretch them to the full width".

**Comment by fabiosantoscode** [comment]
The set of plugins we have seem to be giving high-density images correctly to high-density screens, through a `<picture>` element. I'll create an image that's not up to par and check what happens.

**Comment by fabiosantoscode** [comment]
@shcheklein I've resized an image way down to 264px and observed that the image doesn't get stretched all the way across, and instead sits at 264 *css* pixels wide. This is not retina pixels, so it's not sharp enough. However non-dense images would become tiny if shrunk to the 3x pixel density, so I don't think we should go down that road, and agree with this default behaviour.

To fix potentially small images right at the source, we can add a new check on precommit which ensures that images which have been added are at least 1400 wide and stops the commit otherwise. What do you think?

**Comment by shcheklein** [comment]
@fabiosantoscode not sure I like it, I would force a smaller size (2x, 132 in your case) - just to make sure that it's always the same and it's not confusing to editors. Also, it might be an easy way out of #69 - just make original small enough.

**Comment by fabiosantoscode** [comment]
@shcheklein the existing solution already yields images with always the same proportion. They're just blurrier on higher density screens :smile: 

I've done a ton of docs, issues and source code reading by now.

Perhaps the best option would be to augment #92 by adding some logic to query the image and defining its size right there. The advantage of that is that we won't have to worry about conflicting code setting max-width.

**Comment by shcheklein** [comment]
@fabiosantoscode okay, it might be an option.

>  They're just blurrier on higher density screens

That's the point - I'm trying to understand if there a way to specify somehow to the regular gatsby plugin to limit max width so that they are never blurry?

**Comment by fabiosantoscode** [comment]
I looked for that and found nothing, neither in gatsby-remark-images, or in gatsby-plugin-sharp. Let's wait on #92 and try that option.

**Comment by frontexpert** [comment]
I looked for that a lot of and I understood a bit!

ref https://github.com/gatsbyjs/gatsby/blob/7556cb6f3f52be27083b15c25153f8dfdcc98d98/packages/gatsby-plugin-sharp/src/index.js#L450

## In Medium, the images come original image size. 
![image](https://user-images.githubusercontent.com/19707900/73853638-f5934480-480f-11ea-9f0b-f2ce1559d024.png)_It is size is controlled by CSS_

## In Gatsby, 
in the process of the build, it gets the original image size and verified the value of max-width defined in the gatsby-remark-images and it creates multiple sizes images with the breakpoints 1/4, 1/2, max-width defined, 1.5x, 2x and the original size image 

For example, it defined a max-width: 700px and original size images is 1920px

Gatsby Image will generate  175px width, 350px width, 700px width is defined in config, 1050px width, 1400px and the original size 1920px 

This image has 1920px
![image](https://user-images.githubusercontent.com/19707900/73854991-2a080000-4812-11ea-8e48-db5972eed50a.png)

This image has 3200px
![image](https://user-images.githubusercontent.com/19707900/73855678-2a54cb00-4813-11ea-881a-ea40b8ee5750.png)


Now if the original size image is smaller than defined max-width: 700px

It gets the ref the defined in the config that is max-width: 700px and it will generate 1/4 of 700px that is 175px, 1/2 of 700px that is 350px and now generate the original size image that case is 450px, It don't stretch image.

This image has 450px 
![image](https://user-images.githubusercontent.com/19707900/73856337-0e055e00-4814-11ea-9ec9-e18f71531a48.png)

The image above has 450px original size and below has 1920px original size
![image](https://user-images.githubusercontent.com/19707900/73856906-ef539700-4814-11ea-96ae-039c3cb2af19.png)

In this case, the original image is smaller than 1/4 of size defined 

The gatsby generated here just the original image size!

This image has 144px
![image](https://user-images.githubusercontent.com/19707900/73857500-caabef00-4815-11ea-92fb-5e236613172c.png)

The image above has 144px original size and below has 300px original size
![image](https://user-images.githubusercontent.com/19707900/73857905-5aea3400-4816-11ea-8c4f-f04dd65fc01b.png)

**Comment by shcheklein** [comment]
@frontexpert so, what are the next steps here? did we understand it right that if image is small (let's say 300px) and max-width in Gatsby is set to 800px it will generate code to show 300px as is (not 150px to make it sharp on retina)?

**Comment by frontexpert** [comment]
Next step!
To maintain the quality of sharpness in the retina you should use an image of at least 1400px so that Gatsby manages for all resolutions.

If he uses a smaller image he can blur on the retina screen!

There is no problem in the body of the post, as gatsby defines the max-width without any interference

The problem I found is in the hero of the post! where the application manipulates the image via CSS.


As you can see, this is the same 144px image, but in the hero, it is stretched and in the body of the tag it remains in its original size because it is smaller than is defined in the configuration

![image](https://user-images.githubusercontent.com/19707900/73867394-642ecd00-4825-11ea-85c0-1f84245f95a2.png)

**Comment by shcheklein** [comment]
@frontexpert so, what are the action items for this ticket?

**Comment by frontexpert** [comment]
A solution to this problem would be to create a component to handle the hero image, and when the image is less than the maximum width we will keep the original width and add either a background color or the image itself with a blur to maintain the hero's standard!

Already in the image of the body of the markdown, we must not do anything for the time being to create a doc to inform the writers that whenever possible they should use an image from 1200px to 1800px so that Gatsby manages all the sizes appropriately

**Comment by frontexpert** [comment]
What do you think?

**Comment by shcheklein** [comment]
so, the problem is with `we will keep the original width` - it makes them blurry anyway. We should do 1/2 width in both cases.

also, we already have a bunch of older posts that have blurry images, we should:

1. check that we can't get from medium better resolution (sometimes you can get it by playing with it's URL, changing width, etc)
2. for those we can't get better resolution - we should either apply resize, or force Gatsby to apply 1/2 width in some other way to make them sharp (granted, the might become smaller). To a reasonable extent.

Otherwise, your idea with a hero component sounds good. Would like to see some implementation.

**Comment by frontexpert** [comment]
I'll look a little more for a solution to the problem of blurry

I will implement the new hero component! For you to see
