### ISSUE TITLE
syntax highlighting showing bugs

### ISSUE THREAD

**Issue by andronovhopf** [iterative/blog#82]
DVC syntax highlighting in code blocks seems to have some errors- 

<img width="761" alt="Screen Shot 2020-01-24 at 1 19 24 PM" src="https://user-images.githubusercontent.com/29716724/73104804-27211d00-3eac-11ea-92b5-b7d2138f226b.png">

**Comment by shcheklein** [comment]
@fabiosantoscode could you take a look at this one?

in general we need to update the prism highlighter to be consistent (or better) with the one we have on dvc.org, also to support three level of command `dvc remote add`, etc. And keep JS for it clean and manageable.

**Comment by fabiosantoscode** [comment]
Hey there! I did some digging, and I have a basic understanding of prism and how we're using it.

The reason `python` is being highlighted in the first code block is that it's on the command list. I might be able to fix that one by separating the command part from the argument part.

In the second block `file` is being highlighted for the same reason. I think we can get away with just removing `file` from the command list, as it's not very used.

Lastly, I can try to add `$(...)` to the parsing rules so it turns a different color and commands inside are highlighted like any other command.

I'll try to do these things.

**Comment by shcheklein** [comment]
@fabiosantoscode yes, we can start by using different colors for DVC, Git commands and everything else. Also, please take a look at the way we highlight things on the dvc.org end. It's far from perfect as well, but can get you some ideas.

also, we should think about proper support for third level commands like `dvc remote add` but not `dvc remote python`.

**Comment by fabiosantoscode** [comment]
Got some good news and bad news. I've added the separation of commands and keywords and whatnot. Subcommands work as well, and when there's a semicolon, a new command is allowed to start. I haven't figured out how to color git, dvc and regular old commands differently, but I'll look into that. The bad news, is that due to a prism limitation (it trims the left of the string when it finds a match) I can't enable the `input` pattern, which stops people from copying the command prompt at the start `$ `. Basically, if I match that, I can't tell whether a command is starting at the start of a line, and therefore the `python` part of `dvc remote python` gets highlighted because it doesn't know it's not at the start of a line.

![Screenshot from 2020-01-27 17-38-22](https://user-images.githubusercontent.com/1611595/73199021-fe0ebf80-412b-11ea-99a6-05fbe6b82de3.png)
